# Generated by Django 5.0.6 on 2025-12-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HemogramaReferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parametro",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Parámetro del Hemograma",
                    ),
                ),
                (
                    "valores_normales",
                    models.CharField(max_length=200, verbose_name="Valores Normales"),
                ),
                (
                    "causas_alto",
                    models.TextField(
                        blank=True, null=True, verbose_name="Causas de Valor Alto (↑)"
                    ),
                ),
                (
                    "causas_bajo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Causas de Valor Bajo (↓)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetro de Referencia",
                "verbose_name_plural": "Parámetros de Referencia",
            },
        ),
        migrations.CreateModel(
            name="ResultadoPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_paciente", models.CharField(max_length=150)),
                ("fecha_analisis", models.DateField()),
                (
                    "hb_resultado",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Hemoglobina"
                    ),
                ),
                (
                    "wbc_resultado",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Leucocitos"
                    ),
                ),
                (
                    "plt_resultado",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Plaquetas"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado del Paciente",
                "verbose_name_plural": "Resultados de Pacientes",
                "db_table": "table1",
            },
        ),
    ]
